#!/usr/bin/env python3
"""
Vault Scaffold Generator

Reads firm-config/ via config_loader and generates the complete firm vault
directory structure. This is the empty container that all migrated data will
flow into. Must exist before any case data is migrated.

Generated structure:
    {vault_path}/
    |-- cases/                          # Case subdirectories (populated by migration)
    |-- _entity/{role}/                 # Entity card directories per taxonomy role
    |-- _archive/                       # Post-migration archival
    |-- _quarantine/                    # Failed migration cases
    |-- .obsidian/                      # Obsidian plugin configuration
    |-- Firm Dashboard.md               # Generated by dashboard module (Task 2)

Entity role directories are read from firm-config/taxonomy/entity-roles.md.
If firm-config does not exist, falls back to the PI template defaults.

CLI:
    python scripts/vault_scaffold.py --vault-path /path/to/vault [--config-path /path/to/firm-config]

Exit codes:
    0 -- Success (JSON summary on stdout)
    1 -- Error (error message on stderr)
"""

import argparse
import json
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Add config_loader to import path
# ---------------------------------------------------------------------------
sys.path.insert(0, str(Path(__file__).parent.parent / "roscoe-ai" / "workflow_engine"))

from config_loader import load_firm_config, list_practice_areas

# Import sibling modules
sys.path.insert(0, str(Path(__file__).parent))
from obsidian_config import generate_obsidian_config


# ---------------------------------------------------------------------------
# Default entity roles (fallback when firm-config/ is absent)
# ---------------------------------------------------------------------------
# These match the PI template entity_roles from Phase 2.
# When firm-config/ exists, roles are read from taxonomy/entity-roles.md.
DEFAULT_ENTITY_ROLES = [
    {"id": "treating_provider", "display_name": "Treating Provider"},
    {"id": "adjuster", "display_name": "Insurance Adjuster"},
    {"id": "defense_counsel", "display_name": "Defense Counsel"},
    {"id": "expert_witness", "display_name": "Expert Witness"},
    {"id": "lien_holder", "display_name": "Lien Holder"},
    {"id": "client", "display_name": "Client"},
    {"id": "witness", "display_name": "Witness"},
    {"id": "opposing_party", "display_name": "Opposing Party"},
    {"id": "court", "display_name": "Court"},
]


def _get_entity_roles(config_path: str | None = None) -> list[dict]:
    """Load entity roles from firm-config/ or return defaults.

    Parameters
    ----------
    config_path : str or None
        Explicit path to firm-config/ directory.

    Returns
    -------
    list[dict]
        List of role dicts with at least 'id' and 'display_name' keys.
    """
    result = load_firm_config("taxonomy/entity-roles", config_path)

    if result["_source"] == "defaults":
        return DEFAULT_ENTITY_ROLES

    roles = result["frontmatter"].get("roles", [])
    if not roles:
        return DEFAULT_ENTITY_ROLES

    return roles


def _role_id_to_dirname(role_id: str) -> str:
    """Convert a role ID to a directory name.

    Uses the role ID directly with underscores replaced by hyphens for
    filesystem friendliness and Obsidian wikilink readability.

    Examples:
        treating_provider -> treating-provider
        defense_counsel   -> defense-counsel
        client            -> client
    """
    return role_id.replace("_", "-")


def scaffold_vault(
    vault_path: Path,
    config_path: str | None = None,
) -> dict:
    """Generate the complete vault directory structure.

    Parameters
    ----------
    vault_path : Path
        Where to create the vault root directory.
    config_path : str or None
        Path to firm-config/ directory. Auto-discovers if None.

    Returns
    -------
    dict
        Summary with 'vault_path', 'directories_created', 'config_files_created',
        'entity_roles', and 'practice_areas' keys.
    """
    directories_created: list[str] = []
    config_files_created: list[str] = []

    # -------------------------------------------------------------------
    # 1. Create vault root
    # -------------------------------------------------------------------
    vault_path.mkdir(parents=True, exist_ok=True)

    # -------------------------------------------------------------------
    # 2. Create cases/ directory
    # -------------------------------------------------------------------
    cases_dir = vault_path / "cases"
    cases_dir.mkdir(exist_ok=True)
    directories_created.append("cases/")

    # -------------------------------------------------------------------
    # 3. Create _entity/{role}/ directories from taxonomy
    # -------------------------------------------------------------------
    roles = _get_entity_roles(config_path)
    role_names: list[str] = []

    for role in roles:
        role_id = role.get("id", "")
        if not role_id:
            continue
        dirname = _role_id_to_dirname(role_id)
        entity_dir = vault_path / "_entity" / dirname
        entity_dir.mkdir(parents=True, exist_ok=True)
        directories_created.append(f"_entity/{dirname}/")
        role_names.append(dirname)

    # -------------------------------------------------------------------
    # 4. Create _archive/ directory
    # -------------------------------------------------------------------
    archive_dir = vault_path / "_archive"
    archive_dir.mkdir(exist_ok=True)
    directories_created.append("_archive/")

    # -------------------------------------------------------------------
    # 5. Create _quarantine/ directory
    # -------------------------------------------------------------------
    quarantine_dir = vault_path / "_quarantine"
    quarantine_dir.mkdir(exist_ok=True)
    directories_created.append("_quarantine/")

    # -------------------------------------------------------------------
    # 6. Generate .obsidian/ configuration
    # -------------------------------------------------------------------
    obsidian_files = generate_obsidian_config(vault_path)
    config_files_created.extend(obsidian_files)

    # -------------------------------------------------------------------
    # 7. Discover practice areas for reporting
    # -------------------------------------------------------------------
    practice_areas = list_practice_areas(config_path)

    # -------------------------------------------------------------------
    # 8. Generate Firm Dashboard (if dashboard module is available)
    # -------------------------------------------------------------------
    try:
        from dashboards.firm_dashboard import generate_firm_dashboard
        dashboard_path = generate_firm_dashboard(vault_path)
        config_files_created.append(str(dashboard_path.relative_to(vault_path)))
    except ImportError:
        # Dashboard module not yet available (will be created in Task 2)
        pass

    return {
        "vault_path": str(vault_path),
        "directories_created": directories_created,
        "config_files_created": config_files_created,
        "entity_roles": role_names,
        "practice_areas": practice_areas,
    }


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Generate firm vault directory structure from firm-config/"
    )
    parser.add_argument(
        "--vault-path",
        required=True,
        help="Where to create the vault (required)",
    )
    parser.add_argument(
        "--config-path",
        default=None,
        help="Path to firm-config/ directory (auto-discovers if omitted)",
    )
    args = parser.parse_args()

    vault_path = Path(args.vault_path).resolve()

    try:
        result = scaffold_vault(vault_path, args.config_path)
        print(json.dumps(result, indent=2))
        sys.exit(0)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
